### ISSUE TITLE
Failed to publish metrics when using Play 2.5

### ISSUE THREAD

**Issue by wlk** [codacy/sbt-codacy-coverage#14]
I'm getting following stack trace when running `sbt codacyCoverage`

```
[info] Loading project definition from /home/w/projects/game-arena/project
[info] Set current project to game-arena (in build file:/home/w/projects/game-arena/)
[info] Uploading coverage data...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/w/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/w/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
java.lang.NoSuchMethodError: play.api.libs.json.JsValue.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue;
    at com.codacy.api.client.CodacyClient.com$codacy$api$client$CodacyClient$$parseJson(CodacyClient.scala:98)
    at com.codacy.api.client.CodacyClient$$anonfun$post$1.apply(CodacyClient.scala:65)
    at com.codacy.api.client.CodacyClient$$anonfun$post$1.apply(CodacyClient.scala:53)
    at com.codacy.api.client.CodacyClient.withWSClient(CodacyClient.scala:108)
    at com.codacy.api.client.CodacyClient.post(CodacyClient.scala:53)
    at com.codacy.api.service.CoverageServices.sendReport(CoverageServices.scala:14)
    at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:61)
    at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:48)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:19)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:17)
    at scala.Option.map(Option.scala:145)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:17)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:16)
    at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:32)
    at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:31)
    at scala.Option.map(Option.scala:145)
    at com.codacy.api.helpers.FileHelper$.withCommit(FileHelper.scala:31)
    at com.codacy.api.helpers.FileHelper$.withTokenAndCommit(FileHelper.scala:16)
    at com.codacy.CodacyCoveragePlugin$.com$codacy$CodacyCoveragePlugin$$codacyCoverageCommand(CodacyCoveragePlugin.scala:48)
    at com.codacy.CodacyCoveragePlugin$autoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:23)
    at com.codacy.CodacyCoveragePlugin$autoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:22)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:codacyCoverage) java.lang.NoSuchMethodError: play.api.libs.json.JsValue.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue;
[error] Total time: 2 s, completed Mar 29, 2016 2:49:54 PM
```

This is the project I'm setting this up for: https://github.com/wlk/game-arena

Play 2.5
java version "1.8.0_77"
sbt 0.13.11
scala 2.11

Getting failure also on travis build: https://travis-ci.org/wlk/game-arena/builds/119235375

**Comment by pedrorijo91** [comment]
Hey @wlk,

A quick glance makes me think it may be a dependency conflict problem:
- `NoSuchMethodError` on `play.api.libs.json.JsValue.$bslash(Ljava/lang/String;)Lplay/api/libs/json/JsValue;`
- your project uses Play 2.5
- sbt-codacy-coverage depends on [codacy-api-scala](https://github.com/codacy/codacy-api-scala)
- codacy-api-scala depends on Play 2.3.9: https://github.com/codacy/codacy-api-scala/blob/master/project/Dependencies.scala#L13

We will have a better look as soon as possible

**Comment by machadoit** [comment]
Hey @wlk 

At the moment we don't support projects that use Play 2.5. We're planning on a release that supports it, we will keep you posted.

**Comment by BrendanMachado** [comment]
+1 for adding support fir play 2.5

**Comment by machadoit** [comment]
Hey @wlk @BrendanMachado,

We had evaluated the task, and the play 2.5 is only build for scala 2.11, it may take a while because we need a workaround to the sbt plugins just to scala 2.11.x:

"We can't break binary compatibility for all the sbt 0.13 plugins until we release the next version sbt 0.14 or potentially sbt 1.0, so no Scala 2.11.x sbt until then."

We have added this to the dev team backlog but so far we do not have an estimate on when it will be available.
We’ll be updating its progress as soon as we have a breakthrough on this.

Thanks

**Comment by vromancas** [comment]
+1  Please fix this issue

**Comment by mrfyda** [comment]
Version 1.3.6 should fix the issue!
