### ISSUE TITLE
Codacy not auto-creating directories it needs

### ISSUE THREAD

**Issue by newhoggy** [codacy/sbt-codacy-coverage#20]
```
java.io.FileNotFoundException: /home/ubuntu/pico-atomic/target/scala-2.11/coverage-report/codacy-coverage.json (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at java.io.PrintWriter.<init>(PrintWriter.java:263)
    at com.codacy.api.helpers.FileHelper$.writeJsonToFile(FileHelper.scala:48)
    at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:54)
    at com.codacy.CodacyCoveragePlugin$$anonfun$1.apply(CodacyCoveragePlugin.scala:48)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:19)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1$$anonfun$apply$2.apply(FileHelper.scala:17)
    at scala.Option.map(Option.scala:145)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:17)
    at com.codacy.api.helpers.FileHelper$$anonfun$withTokenAndCommit$1.apply(FileHelper.scala:16)
    at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:32)
    at com.codacy.api.helpers.FileHelper$$anonfun$withCommit$2.apply(FileHelper.scala:31)
    at scala.Option.map(Option.scala:145)
    at com.codacy.api.helpers.FileHelper$.withCommit(FileHelper.scala:31)
    at com.codacy.api.helpers.FileHelper$.withTokenAndCommit(FileHelper.scala:16)
    at com.codacy.CodacyCoveragePlugin$.com$codacy$CodacyCoveragePlugin$$codacyCoverageCommand(CodacyCoveragePlugin.scala:48)
    at com.codacy.CodacyCoveragePlugin$autoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:23)
    at com.codacy.CodacyCoveragePlugin$autoImport$$anonfun$baseSettings$2.apply(CodacyCoveragePlugin.scala:22)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (pico-atomic-project/*:codacyCoverage) java.io.FileNotFoundException: /home/ubuntu/pico-atomic/target/scala-2.11/coverage-report/codacy-coverage.json (No such file or directory)
```

Creating the directory allows the plugin to complete:

```
mkdir -p /home/ubuntu/pico-atomic/target/scala-2.11/coverage-report/
```

**Comment by ssemichev** [comment]
I have the same error
java.io.FileNotFoundException: <project path>/target/scala-2.11/coverage-report/codacy-coverage.json (No such file or directory)

Your workaround works, thank you

**Comment by pedrorijo91** [comment]
Hi @newhoggy 

can you provide us a few more details?
- in which project is it happening ? (assuming it is open source)
- what's the sequence of commands you are using?
- what's your OS?
- what is the scala and sbt version of your project?

**Comment by pedrorijo91** [comment]
Closing until more information is available

**Comment by mthmulders** [comment]
I'm also facing this issue. Here's [a repo](https://github.com/mthmulders/sbt-codacy-coverage-issue-20).

Environment:
- macOS 10.12.6
- Java 1.8.0_60 (build 1.8.0_60-b27)
- Scala 2.11.7
- SBT 0.13.16

Could you please re-open and investigate?
