### ISSUE TITLE
Plugin failed to upload data: Request handler not found

### ISSUE THREAD

**Issue by onema** [codacy/sbt-codacy-coverage#57]
### Are you looking for help?

Yes, 

I continue to get misc errors when publishing the coverage report

### Scala Version (2.12.6 / etc)
`2.12.6`

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Alpine 3.8

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
### Library Dependencies
```
libraryDependencies ++= {
    val awsSdkVersion = "1.11.380"
    Seq(
       "io.onema"                   % "json-extensions_2.12"                % "0.3.0",
      "com.amazonaws"               % "aws-lambda-java-events"              % "2.2.2",
      "com.amazonaws"               % "aws-lambda-java-core"                % "1.2.0",
      "com.amazonaws"               % "aws-java-sdk-sns"                    % awsSdkVersion,
      "com.amazonaws"               % "aws-java-sdk-ssm"                    % awsSdkVersion,
      "com.amazonaws"               % "aws-java-sdk-dynamodb"               % awsSdkVersion,
      "com.amazonaws.serverless"    % "aws-serverless-java-container-core"  % "0.9.1",
      "org.apache.httpcomponents"   % "httpcore"                            % "4.4.8",
      "com.typesafe.scala-logging"  %% "scala-logging"                      % "3.7.2",
      "ch.qos.logback"              % "logback-classic"                     % "1.1.7",
      "org.scalatest"               % "scalatest_2.12"                      % "3.0.5"   % Test,
      "org.scalamock"               %% "scalamock"                          % "4.1.0"   % Test
    )
  }
 ``` 
### Expected Behavior

When submitting a pull request from GitHub, it triggers my automated build in AWS CodeBuild. This runs the following commands:
```bash
      sbt clean coverage test
      sbt coverageReport
      sbt codacyCoverage
```
The report should be correctly submitted in codacy

### Actual Behavior
`sbt codacyCoverage` fails at random times:
```
Running command sbt codacyCoverage
Loading settings from plugins.sbt ...
Loading project definition from /codebuild/output/src266778701/src/github.com/onema/uServerless/project
Loading settings from build.sbt ...
Set current project to userverless (in build file:/codebuild/output/src266778701/src/github.com/onema/uServerless/)
Uploading coverage data...
java.lang.RuntimeException: Failed to upload data. Reason: Request handler not found: /2.0/coverage/pr/4/scala
	at scala.sys.package$.error(package.scala:27)
	at com.codacy.CodacyCoveragePlugin$.$anonfun$codacyCoverageCommand$9(CodacyCoveragePlugin.scala:82)
	at com.codacy.api.helpers.FileHelper$.$anonfun$withTokenAndCommit$3(FileHelper.scala:21)
	at scala.Option.map(Option.scala:146)
	at com.codacy.api.helpers.FileHelper$.$anonfun$withTokenAndCommit$1(FileHelper.scala:19)
	at com.codacy.api.helpers.FileHelper$.$anonfun$withCommit$2(FileHelper.scala:34)
	at scala.Option.map(Option.scala:146)
	at com.codacy.api.helpers.FileHelper$.withCommit(FileHelper.scala:33)
	at com.codacy.api.helpers.FileHelper$.withTokenAndCommit(FileHelper.scala:18)
	at com.codacy.CodacyCoveragePlugin$.com$codacy$CodacyCoveragePlugin$$codacyCoverageCommand(CodacyCoveragePlugin.scala:67)
	at com.codacy.CodacyCoveragePlugin$AutoImport$.$anonfun$baseSettings$1(CodacyCoveragePlugin.scala:34)
	at com.codacy.CodacyCoveragePlugin$AutoImport$.$anonfun$baseSettings$1$adapted(CodacyCoveragePlugin.scala:31)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
	at sbt.std.Transform$$anon$4.work(System.scala:66)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:272)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
([31mcodacyCoverage) Failed to upload data. Reason: Request handler not found: /2.0/coverage/pr/4/scala
Total time: 1 s, completed Sep 9, 2018 8:40:50 PM
```

### Reproducible Test Case

This seems to happen for any PR. CodeBuild `CODEBUILD_SOURCE_VERSION` is `pr/#` for pull requests.

**Comment by onema** [comment]
At this time, I'm able to bypass this issue by using a condition in my `buildspec.yml` that skips the coverage report if the `CODEBUILD_SOURCE_VERSION` does not match a git-sha:

```yml
      - echo Submit coverage report to Codacy
      - if [[ $CODEBUILD_SOURCE_VERSION =~ [0-9a-f]{5,40} ]] ; then sbt codacyCoverage; fi
```

Is this an issue with the plugin? or is something I have to live with when using codebuild?

**Comment by rtfpessoa** [comment]
Hi @onema, isn't the content of `CODEBUILD_SOURCE_VERSION` always the commit uuid being built?

**Comment by onema** [comment]
According to the docs 

> CODEBUILD_SOURCE_VERSION: For Amazon S3, the version ID associated with the input artifact. For AWS CodeCommit, the commit ID or branch name associated with the version of the source code to be built. For CODEBUILD_RESOLVED_SOURCE_VERSIONGitHub, the commit ID, branch name, or tag name associated with the version of the source code to be built.

I’m not sure why the pr is a special case :(

**Comment by rtfpessoa** [comment]
We always need a commit to submit coverage. I think the best we can do is remove that variable and you can pass the commit from the CLI.

**Comment by onema** [comment]
I found this in the AWS forums: [Github pull requests are built twice]( https://forums.aws.amazon.com/thread.jspa?messageID=843572&tstart=0)

Basically, the simplest thing to do is to disable the PR from the CodeBuild webhook.

The GitHub checks will still run and get reported on PRs as long as the `push` event triggers CodeBuild.

![screen shot 2018-09-10 at 1 10 30 pm](https://user-images.githubusercontent.com/532616/45321882-6c34f100-b4fb-11e8-8093-935149744925.png)

I'm closing this issue, as I consider this being a CodeBuild problem and not a plugin problem. 

As usuall, thank you for the quick response!

**Comment by onema** [comment]
For reference, this is the CodeBuild definition I've been using

[codebuild-4scala_cfn.yml](https://gist.github.com/onema/c67429e13f77dd2aa9fc15e9a95fdb13)
